name: Upload User Banner

on:
  workflow_dispatch:
    inputs:
      user_id:
        description: 'Player ID'
        required: true
        default: '1482160526657196223'
      image_url: 
        description: 'Image URL (Copy image address)'
        required: true
        default: 'https://media.discordapp.net/attachments/1492498485751189564/1504593564800385205/Untitled-1.png?ex=6a1ff133&is=6a1e9fb3&hm=b16a07b34e750131e0e03afa6e24a1d80442fcfde1e058bfc92a5504e6308846&=&format=webp&quality=lossless&width=508&height=90'
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download image
        run: |
          mkdir -p banners
          curl -L "${{ github.event.inputs.image_url }}" -o "banners/${{ github.event.inputs.user_id }}.png"

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add banners/
          git commit -m "Add banner for player ${{ github.event.inputs.user_id }}"
          git push
